@token = {{$processEnv USER_TOKEN}}
@applicationId=PROlqK-Y_ryNbOvhgfIL4

### Get all comments for an application
GET http://localhost:3000/api/applications/{{applicationId}}/comments
Cookie: {{token}}

### @name createComment
POST http://localhost:3000/api/applications/{{applicationId}}/comments
Cookie: {{token}}
Content-Type: application/json

{
    "comment": "This is a test comment for the application"
}


#### 
@commentId = {{createComment.response.body.$.id}}

### Delete a comment
DELETE http://localhost:3000/api/applications/{{applicationId}}/comments/{{commentId}}
Cookie: {{token}}

### Get user comments (default pagination - page 1, limit 10)
GET http://localhost:3000/api/comments
Cookie: {{token}}

### Get user comments with custom pagination (page 2, limit 20)
GET http://localhost:3000/api/comments?page=2&limit=20
Cookie: {{token}}

### Get user comments with invalid pagination (should return 400)
GET http://localhost:3000/api/comments?page=0&limit=200
Cookie: {{token}}

### Get user comments without authentication (should return 401)
GET http://localhost:3000/api/comments 