#:schema node_modules/wrangler/config-schema.json
name = "applications-assistant"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "job-assistant"
database_id = "c2ff5544-1e66-4360-94f9-eccec895df75"